add_newline = false


## [](fg:#fbf1c7)\
##
## [   ](fg:#fbf1c7)\
## [  ](fg:#fbf1c7)\
##
##[ ](fg:#fbf1c7 )\
##
## [  ](fg:#d79921)\
##
##
format = """\
[](fg:#fbf1c7)\
$directory\


[  ](fg:#fbf1c7)\
$git_branch\
$git_status\

$c\
$cpp\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\


[\n ](fg:n;;one)\

$character\
[  ](fg:#fbf1c7)\
"""



# $docker_context\
# [](fg:#06969A)\
#   		▶  		▹  ➤		➤  ▶		▶  ▸		▸



# RIGHT SIDE --
right_format = """\
$cmd_duration\
[ ](fg:#fbf1c7)\
${custom.time-char}\
[    ](fg:#fbf1c7)\
"""

# using fish function (right_prompt_starship)
[custom.time-char]
command="right_prompt_starship"
when=true
style = "fg:#fbf1c7"
format = '[$output]($style)'


[cmd_duration]
min_time = 500
format = '[$duration](bold yellow) '
# -------------






[character]
success_symbol="[](#06d66A)"
error_symbol="[](#ff7575)"
format="$symbol"



#[custom.moon]
#when = true
#style="fg:#fbf1c7"
#command = "$HOME/.config/myscripts/moon-face/moon-face-print --mode 2"
#format = "[$output]($style)"



[directory]
home_symbol =       "   ~"
read_only=          "  !"
repo_root_format= '[$before_root_path]($before_repo_root_style)[  ](#aD90ff)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'
truncation_symbol = ' ../'
fish_style_pwd_dir_length=4
truncation_length = 2
use_logical_path=true
truncate_to_repo=false
before_repo_root_style="#9DC183"
repo_root_style="bold yellow"
style = "fg:#fbf1c7"
read_only_style="fg:#ff7575"

format = "[$read_only]($read_only_style)[$path]($style)"
# shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
#[directory.substitutions]
#"Desktop"=" "
#"Documents" = "󰈙 "
#"Downloads" = " "
#"Media" = "   "
#"Music" = " "
#"Pictures" = " "
#"Videos" = " "
#"myworld" = " "
#"WorkSpace"="󱎃 "
#"web"=""
#"test"="󰙨 "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "



[git_branch]
symbol = ""
style = "fg:#689d6a"
format = '[$symbol $branch ]($style)'

[git_status]
style = "fg:#fb4934"
format = '[$all_status$ahead_behind]($style)'



#[docker_context]
#symbol = " "
#style = "fg:#458588"
#format = '[ $symbol $context ]($style)'





# ---- LANGS ----
[c]
symbol = " "
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'

[gradle]
symbol = " "
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#d79921"
format = '[ $symbol ($version) ]($style)'
# ---- END LANGS ----
